services:
  api:
    build:
      context: .
      dockerfile: deploy/docker/api.Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - apps/api/.env
    volumes:
      - ./:/app
  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - api
